/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppActiviteRouteImport } from './routes/_app/activite'
import { Route as AppAnalytiqueRouteImport } from './routes/_app/analytique'
import { Route as AppBeneficiairesRouteImport } from './routes/_app/beneficiaires'
import { Route as AppCarteRouteImport } from './routes/_app/carte'
import { Route as AppConventionsRouteImport } from './routes/_app/conventions'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppOddsRouteImport } from './routes/_app/odds'
import { Route as AppParametresRouteImport } from './routes/_app/parametres'
import { Route as AppRechercheRouteImport } from './routes/_app/recherche'
import { Route as AppTableauRouteImport } from './routes/_app/tableau'
import { Route as AppCooperativesIndexRouteImport } from './routes/_app/cooperatives/index'
import { Route as AppCooperativesIdRouteImport } from './routes/_app/cooperatives/$id'
import { Route as AppRapportsIndexRouteImport } from './routes/_app/rapports/index'
import { Route as AppRapportsIdRouteImport } from './routes/_app/rapports/$id'
import { Route as AppRapportsNouveauRouteImport } from './routes/_app/rapports/nouveau'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActiviteRoute = AppActiviteRouteImport.update({
  id: '/activite',
  path: '/activite',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalytiqueRoute = AppAnalytiqueRouteImport.update({
  id: '/analytique',
  path: '/analytique',
  getParentRoute: () => AppRoute,
} as any)
const AppBeneficiairesRoute = AppBeneficiairesRouteImport.update({
  id: '/beneficiaires',
  path: '/beneficiaires',
  getParentRoute: () => AppRoute,
} as any)
const AppCarteRoute = AppCarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => AppRoute,
} as any)
const AppConventionsRoute = AppConventionsRouteImport.update({
  id: '/conventions',
  path: '/conventions',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOddsRoute = AppOddsRouteImport.update({
  id: '/odds',
  path: '/odds',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppRechercheRoute = AppRechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => AppRoute,
} as any)
const AppTableauRoute = AppTableauRouteImport.update({
  id: '/tableau',
  path: '/tableau',
  getParentRoute: () => AppRoute,
} as any)
const AppCooperativesIndexRoute = AppCooperativesIndexRouteImport.update({
  id: '/cooperatives/',
  path: '/cooperatives/',
  getParentRoute: () => AppRoute,
} as any)
const AppCooperativesIdRoute = AppCooperativesIdRouteImport.update({
  id: '/cooperatives/$id',
  path: '/cooperatives/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRapportsIndexRoute = AppRapportsIndexRouteImport.update({
  id: '/rapports/',
  path: '/rapports/',
  getParentRoute: () => AppRoute,
} as any)
const AppRapportsIdRoute = AppRapportsIdRouteImport.update({
  id: '/rapports/$id',
  path: '/rapports/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRapportsNouveauRoute = AppRapportsNouveauRouteImport.update({
  id: '/rapports/nouveau',
  path: '/rapports/nouveau',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activite': typeof AppActiviteRoute
  '/analytique': typeof AppAnalytiqueRoute
  '/beneficiaires': typeof AppBeneficiairesRoute
  '/carte': typeof AppCarteRoute
  '/conventions': typeof AppConventionsRoute
  '/documents': typeof AppDocumentsRoute
  '/import': typeof AppImportRoute
  '/notifications': typeof AppNotificationsRoute
  '/odds': typeof AppOddsRoute
  '/parametres': typeof AppParametresRoute
  '/recherche': typeof AppRechercheRoute
  '/tableau': typeof AppTableauRoute
  '/cooperatives/$id': typeof AppCooperativesIdRoute
  '/rapports/$id': typeof AppRapportsIdRoute
  '/rapports/nouveau': typeof AppRapportsNouveauRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cooperatives/': typeof AppCooperativesIndexRoute
  '/rapports/': typeof AppRapportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activite': typeof AppActiviteRoute
  '/analytique': typeof AppAnalytiqueRoute
  '/beneficiaires': typeof AppBeneficiairesRoute
  '/carte': typeof AppCarteRoute
  '/conventions': typeof AppConventionsRoute
  '/documents': typeof AppDocumentsRoute
  '/import': typeof AppImportRoute
  '/notifications': typeof AppNotificationsRoute
  '/odds': typeof AppOddsRoute
  '/parametres': typeof AppParametresRoute
  '/recherche': typeof AppRechercheRoute
  '/tableau': typeof AppTableauRoute
  '/cooperatives/$id': typeof AppCooperativesIdRoute
  '/rapports/$id': typeof AppRapportsIdRoute
  '/rapports/nouveau': typeof AppRapportsNouveauRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cooperatives': typeof AppCooperativesIndexRoute
  '/rapports': typeof AppRapportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/activite': typeof AppActiviteRoute
  '/_app/analytique': typeof AppAnalytiqueRoute
  '/_app/beneficiaires': typeof AppBeneficiairesRoute
  '/_app/carte': typeof AppCarteRoute
  '/_app/conventions': typeof AppConventionsRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/import': typeof AppImportRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/odds': typeof AppOddsRoute
  '/_app/parametres': typeof AppParametresRoute
  '/_app/recherche': typeof AppRechercheRoute
  '/_app/tableau': typeof AppTableauRoute
  '/_app/cooperatives/$id': typeof AppCooperativesIdRoute
  '/_app/rapports/$id': typeof AppRapportsIdRoute
  '/_app/rapports/nouveau': typeof AppRapportsNouveauRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/cooperatives/': typeof AppCooperativesIndexRoute
  '/_app/rapports/': typeof AppRapportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activite'
    | '/analytique'
    | '/beneficiaires'
    | '/carte'
    | '/conventions'
    | '/documents'
    | '/import'
    | '/notifications'
    | '/odds'
    | '/parametres'
    | '/recherche'
    | '/tableau'
    | '/cooperatives/$id'
    | '/rapports/$id'
    | '/rapports/nouveau'
    | '/api/auth/$'
    | '/cooperatives/'
    | '/rapports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activite'
    | '/analytique'
    | '/beneficiaires'
    | '/carte'
    | '/conventions'
    | '/documents'
    | '/import'
    | '/notifications'
    | '/odds'
    | '/parametres'
    | '/recherche'
    | '/tableau'
    | '/cooperatives/$id'
    | '/rapports/$id'
    | '/rapports/nouveau'
    | '/api/auth/$'
    | '/cooperatives'
    | '/rapports'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/activite'
    | '/_app/analytique'
    | '/_app/beneficiaires'
    | '/_app/carte'
    | '/_app/conventions'
    | '/_app/documents'
    | '/_app/import'
    | '/_app/notifications'
    | '/_app/odds'
    | '/_app/parametres'
    | '/_app/recherche'
    | '/_app/tableau'
    | '/_app/cooperatives/$id'
    | '/_app/rapports/$id'
    | '/_app/rapports/nouveau'
    | '/api/auth/$'
    | '/_app/cooperatives/'
    | '/_app/rapports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activite': {
      id: '/_app/activite'
      path: '/activite'
      fullPath: '/activite'
      preLoaderRoute: typeof AppActiviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytique': {
      id: '/_app/analytique'
      path: '/analytique'
      fullPath: '/analytique'
      preLoaderRoute: typeof AppAnalytiqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beneficiaires': {
      id: '/_app/beneficiaires'
      path: '/beneficiaires'
      fullPath: '/beneficiaires'
      preLoaderRoute: typeof AppBeneficiairesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carte': {
      id: '/_app/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof AppCarteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conventions': {
      id: '/_app/conventions'
      path: '/conventions'
      fullPath: '/conventions'
      preLoaderRoute: typeof AppConventionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/odds': {
      id: '/_app/odds'
      path: '/odds'
      fullPath: '/odds'
      preLoaderRoute: typeof AppOddsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres': {
      id: '/_app/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recherche': {
      id: '/_app/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof AppRechercheRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tableau': {
      id: '/_app/tableau'
      path: '/tableau'
      fullPath: '/tableau'
      preLoaderRoute: typeof AppTableauRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cooperatives/': {
      id: '/_app/cooperatives/'
      path: '/cooperatives'
      fullPath: '/cooperatives/'
      preLoaderRoute: typeof AppCooperativesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cooperatives/$id': {
      id: '/_app/cooperatives/$id'
      path: '/cooperatives/$id'
      fullPath: '/cooperatives/$id'
      preLoaderRoute: typeof AppCooperativesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rapports/': {
      id: '/_app/rapports/'
      path: '/rapports'
      fullPath: '/rapports/'
      preLoaderRoute: typeof AppRapportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rapports/$id': {
      id: '/_app/rapports/$id'
      path: '/rapports/$id'
      fullPath: '/rapports/$id'
      preLoaderRoute: typeof AppRapportsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rapports/nouveau': {
      id: '/_app/rapports/nouveau'
      path: '/rapports/nouveau'
      fullPath: '/rapports/nouveau'
      preLoaderRoute: typeof AppRapportsNouveauRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppActiviteRoute: typeof AppActiviteRoute
  AppAnalytiqueRoute: typeof AppAnalytiqueRoute
  AppBeneficiairesRoute: typeof AppBeneficiairesRoute
  AppCarteRoute: typeof AppCarteRoute
  AppConventionsRoute: typeof AppConventionsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppImportRoute: typeof AppImportRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOddsRoute: typeof AppOddsRoute
  AppParametresRoute: typeof AppParametresRoute
  AppRechercheRoute: typeof AppRechercheRoute
  AppTableauRoute: typeof AppTableauRoute
  AppCooperativesIdRoute: typeof AppCooperativesIdRoute
  AppRapportsIdRoute: typeof AppRapportsIdRoute
  AppRapportsNouveauRoute: typeof AppRapportsNouveauRoute
  AppCooperativesIndexRoute: typeof AppCooperativesIndexRoute
  AppRapportsIndexRoute: typeof AppRapportsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActiviteRoute: AppActiviteRoute,
  AppAnalytiqueRoute: AppAnalytiqueRoute,
  AppBeneficiairesRoute: AppBeneficiairesRoute,
  AppCarteRoute: AppCarteRoute,
  AppConventionsRoute: AppConventionsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppImportRoute: AppImportRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOddsRoute: AppOddsRoute,
  AppParametresRoute: AppParametresRoute,
  AppRechercheRoute: AppRechercheRoute,
  AppTableauRoute: AppTableauRoute,
  AppCooperativesIdRoute: AppCooperativesIdRoute,
  AppRapportsIdRoute: AppRapportsIdRoute,
  AppRapportsNouveauRoute: AppRapportsNouveauRoute,
  AppCooperativesIndexRoute: AppCooperativesIndexRoute,
  AppRapportsIndexRoute: AppRapportsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
